allowed_keys:
  - id
  - nationbuilder_id
  - email
  - email1
  - email2
  - email3
  - email4
  - username
  - first_name
  - last_name
  - full_name
  - primary_address
  - tags
  - bio
  - occupation
  - profile_content
  - twitter_login
  - facebook_username
  - facebook_profile_url
  - linkedin_id
  - website
  - profile_image_url_ssl
  - banned_at